package com.rbs.testharness.common;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.text.DecimalFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Component;
import org.springframework.util.ResourceUtils;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.rbs.testharness.model.PricingTestCaseResponse;

@Component
public class GeneratePdfReport{

    private static final Logger logger = LoggerFactory.getLogger(GeneratePdfReport.class);

    public ByteArrayInputStream testCaseResultReport(List<PricingTestCaseResponse> pricingTestCaseResponse) {

        Document document = new Document();
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        List<PricingTestCaseResponse> passedList=new ArrayList<>();
        List<PricingTestCaseResponse> failedList=new ArrayList<>();
        float totalTestCase=0;
        if(null!=pricingTestCaseResponse && pricingTestCaseResponse.size()>0) {
        	totalTestCase=pricingTestCaseResponse.size();
        	for(PricingTestCaseResponse testCases : pricingTestCaseResponse) {
        		if(null!=testCases.getTestTransactionFlag() && "Y".equalsIgnoreCase((testCases.getTestTransactionFlag().toString()))) {
        			passedList.add(testCases);
        		}else {
        			failedList.add(testCases);
        		}
        	}
        }
        //Calculation of failed and passed %
        float passedCaseSize=passedList!=null && passedList.size()>0?passedList.size():0;
        float failedCaseSize=failedList!=null && failedList.size()>0?failedList.size():0;
        
        float passedPercentage=passedCaseSize!=0?passedCaseSize*100/totalTestCase:0;
        float failedPercentage=failedCaseSize!=0?failedCaseSize*100/totalTestCase:0;
        DecimalFormat dformat=new DecimalFormat("0.00");
        List<List<PricingTestCaseResponse>> totalTestCaseList=new ArrayList<>();
        totalTestCaseList.add(passedList);
        totalTestCaseList.add(failedList);
        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");  
        LocalDateTime generatedTime = LocalDateTime.now();  
        
        try {
        	//Reading Image file
            ClassPathResource imageFile = new ClassPathResource("static/header_image.png");
           // Image image = Image.getInstance("D:\\Java_project_workspace\\project_workspace\\testharness\\src\\main\\resources\\static\\header_image.png");
            File file = ResourceUtils.getFile("classpath:static/header_image.png");
            Image image = Image.getInstance(file.getAbsolutePath());
            System.out.println("path "+file.getAbsolutePath());
            image.scalePercent(100f);
            image.setAbsolutePosition(0, (float) (PageSize.A4.getHeight()- 40.0));
            image.scaleToFit(597f, 597f);
            
            Font paraFont = new Font(Font.FontFamily.TIMES_ROMAN, 6.5f, Font.BOLD);
            Paragraph para = new Paragraph();
            para.add(" \n ");
            para.add("Report Generated on : "+dtf.format(generatedTime)+"                                        Generated By : Goutam");
            para.setFont(paraFont);
            para.add(" \n ");
            
           /* Font boldFont = new Font(Font.FontFamily.TIMES_ROMAN, 10.5f, Font.BOLD);
            Chunk chunk = new Chunk("Passed : "+dformat.format(passedPercentage)+"%",boldFont);
            chunk.setBackground(BaseColor.ORANGE);
            Paragraph para2 = new Paragraph(chunk);
            para2.setAlignment(Element.ALIGN_RIGHT);
            para2.add(" \n ");*/
            
            
            Font lableFont = FontFactory.getFont(FontFactory.TIMES_ROMAN, 8.5f);
            lableFont.setColor(BaseColor.WHITE);
            Font valueFont = FontFactory.getFont(FontFactory.TIMES_ROMAN, 7.5f);


        	PdfPTable resultSummaryTable = new PdfPTable(3);
        	resultSummaryTable.setWidthPercentage(30);
         	resultSummaryTable.setWidths(new float[]{4f, 2f, 2f});
         	resultSummaryTable.setSpacingAfter(15f);
         	resultSummaryTable.setHorizontalAlignment(Element.ALIGN_RIGHT);
        	
        	PdfPCell summarycell;
        	summarycell = new PdfPCell(new Phrase("Total Test Case", lableFont));
         	summarycell.setBackgroundColor(new BaseColor(43, 56,176));
        	summarycell.setHorizontalAlignment(Element.ALIGN_CENTER);
        	resultSummaryTable.addCell(summarycell);

            summarycell = new PdfPCell(new Phrase("Passed", lableFont));
         	summarycell.setBackgroundColor(new BaseColor(43, 56,176));
            summarycell.setHorizontalAlignment(Element.ALIGN_CENTER);
            resultSummaryTable.addCell(summarycell);

            summarycell = new PdfPCell(new Phrase("Failed", lableFont));
         	summarycell.setBackgroundColor(new BaseColor(43, 56,176));
            summarycell.setHorizontalAlignment(Element.ALIGN_CENTER);
            resultSummaryTable.addCell(summarycell);
            
            PdfPCell scell;
            scell = new PdfPCell(new Phrase(String.valueOf((int)totalTestCase),valueFont));
            scell.setBackgroundColor(BaseColor.ORANGE);
            scell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            scell.setHorizontalAlignment(Element.ALIGN_CENTER);
            resultSummaryTable.addCell(scell);

            scell = new PdfPCell(new Phrase(String.valueOf((int)passedCaseSize),valueFont));
            scell.setPaddingLeft(5);
            scell.setBackgroundColor(BaseColor.GREEN);
            scell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            scell.setHorizontalAlignment(Element.ALIGN_CENTER);
            resultSummaryTable.addCell(scell);

            scell = new PdfPCell(new Phrase(String.valueOf((int)failedCaseSize),valueFont));
            scell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            scell.setBackgroundColor(BaseColor.RED);
            scell.setHorizontalAlignment(Element.ALIGN_CENTER);
            scell.setPaddingRight(5);
            resultSummaryTable.addCell(scell);  
            
            PdfWriter writer = PdfWriter.getInstance(document, out);
            // add header and footer
            GeneratePdfHeaderFooterEvent event = new GeneratePdfHeaderFooterEvent();
            writer.setPageEvent(event);
            
            document.setPageSize(PageSize.A4);
            document.setMargins(50, 50, 120, 50);
            document.setMarginMirroring(false);
            document.open();
            //Rectangle rect= new Rectangle(577,825,18,15);
            //rect.setBorder(Rectangle.BOX);
            //rect.setBorderWidth(2);
           // document.add(rect);
           // document.add(image);
            //document.add(para);
            document.add(resultSummaryTable);
           // document.add(para2);
            
            //Test Case Table
            
            PdfPTable table=null;
            PdfPCell cell=null;
            int i=0;
            for(List<PricingTestCaseResponse> testCasesList : totalTestCaseList) {
            	if(testCasesList!=null && testCasesList.size()>0) {
	            	for(PricingTestCaseResponse cases : testCasesList) {
	            		if(null!=cases.getTestTransactionFlag())
	                        if("Y".equalsIgnoreCase(cases.getTestTransactionFlag().toString())) {
	                        	Font boldFont1 = new Font(Font.FontFamily.TIMES_ROMAN, 10.5f, Font.BOLD);
	                            Chunk chunk1 = new Chunk("Passed :"+dformat.format(passedPercentage) +"%",boldFont1);
	                            chunk1.setBackground(BaseColor.ORANGE);
	                            Paragraph para3 = new Paragraph(chunk1);
	                            para3.setAlignment(Element.ALIGN_RIGHT);
	                            para3.add(" \n ");
	                            document.add(para3);
	                            break;
	                        }else {
	                        	Font boldFont1 = new Font(Font.FontFamily.TIMES_ROMAN, 10.5f, Font.BOLD);
	                            Chunk chunk1 = new Chunk("Failed :"+dformat.format(failedPercentage) +"%",boldFont1);
	                            chunk1.setBackground(BaseColor.ORANGE);
	                            Paragraph para3 = new Paragraph(chunk1);
	                            para3.setAlignment(Element.ALIGN_RIGHT);
	                            para3.add(" \n ");
	                            document.add(para3);
	                            break;
	                        }
	            	}
	            	
	            	table=new PdfPTable(13);
	                table.setWidthPercentage(100);
	                table.setWidths(new float[]{1f, 1.5f, 1.5f,1.5f, 1.5f,1.5f, 1.5f,1.5f, 1.5f,1.5f, 1.5f,1.5f, 1.5f});
	
	
	                PdfPCell hcell;
	                hcell = new PdfPCell(new Phrase("Id", lableFont));
	                hcell.setHorizontalAlignment(Element.ALIGN_CENTER);
	                hcell.setBackgroundColor(new BaseColor(43, 56,176));
	                table.addCell(hcell);
	
	                hcell = new PdfPCell(new Phrase("Application Identity", lableFont));
	                hcell.setHorizontalAlignment(Element.ALIGN_CENTER);
	                hcell.setBackgroundColor(new BaseColor(43, 56,176));
	                table.addCell(hcell);
	
	                hcell = new PdfPCell(new Phrase("Bank Division", lableFont));
	                hcell.setHorizontalAlignment(Element.ALIGN_CENTER);
	                hcell.setBackgroundColor(new BaseColor(43, 56,176));
	                table.addCell(hcell);
	
	                hcell = new PdfPCell(new Phrase("Product Family", lableFont));
	                hcell.setHorizontalAlignment(Element.ALIGN_CENTER);
	                hcell.setBackgroundColor(new BaseColor(43, 56,176));
	                table.addCell(hcell);
	
	                hcell = new PdfPCell(new Phrase("Product Name", lableFont));
	                hcell.setHorizontalAlignment(Element.ALIGN_CENTER);
	                hcell.setBackgroundColor(new BaseColor(43, 56,176));
	                table.addCell(hcell);
	
	                hcell = new PdfPCell(new Phrase("Borrowing Amount", lableFont));
	                hcell.setHorizontalAlignment(Element.ALIGN_CENTER);
	                hcell.setBackgroundColor(new BaseColor(43, 56,176));
	                table.addCell(hcell);
	                
	                hcell = new PdfPCell(new Phrase("Term(Months)", lableFont));
	                hcell.setHorizontalAlignment(Element.ALIGN_CENTER);
	                hcell.setBackgroundColor(new BaseColor(43, 56,176));
	                table.addCell(hcell);
	
	                hcell = new PdfPCell(new Phrase("Risk Band", lableFont));
	                hcell.setHorizontalAlignment(Element.ALIGN_CENTER);
	                hcell.setBackgroundColor(new BaseColor(43, 56,176));
	                table.addCell(hcell);
	                
	                hcell = new PdfPCell(new Phrase("Expected AIR", lableFont));
	                hcell.setHorizontalAlignment(Element.ALIGN_CENTER);
	                hcell.setBackgroundColor(new BaseColor(43, 56,176));
	                table.addCell(hcell);
	
	                hcell = new PdfPCell(new Phrase("Excepted APR", lableFont));
	                hcell.setHorizontalAlignment(Element.ALIGN_CENTER);
	                hcell.setBackgroundColor(new BaseColor(43, 56,176));
	                table.addCell(hcell);
	                
	                hcell = new PdfPCell(new Phrase("Actual AIR", lableFont));
	                hcell.setHorizontalAlignment(Element.ALIGN_CENTER);
	                hcell.setBackgroundColor(new BaseColor(43, 56,176));
	                table.addCell(hcell);
	
	                hcell = new PdfPCell(new Phrase("Actual APR", lableFont));
	                hcell.setHorizontalAlignment(Element.ALIGN_CENTER);
	                hcell.setBackgroundColor(new BaseColor(43, 56,176));
	                table.addCell(hcell);
	
	                hcell = new PdfPCell(new Phrase("Pass/Fail", lableFont));
	                hcell.setHorizontalAlignment(Element.ALIGN_CENTER);
	                hcell.setBackgroundColor(new BaseColor(43, 56,176));
	                table.addCell(hcell);
	            	
	                //Generate records	
	                generatePassedFailedReport(cell,table,testCasesList,valueFont);
	                document.add(table);
            	}
            }
       
            /*PdfWriter.getInstance(document, out);
            document.open();
            Rectangle rect= new Rectangle(577,825,18,15);
            rect.setBorder(Rectangle.BOX);
            rect.setBorderWidth(2);
           // document.add(rect);
            document.add(image);
            document.add(para);
            document.add(resultSummaryTable);
            document.add(para2);*/
            //Creating boarder 
           // rect.setBorder(Rectangle.BOX);
            //rect.setBorderWidth(2);
           // document.add(rect);
            document.close();

        } catch (Exception ex) {

            logger.error("Error occurred: {0}", ex);
        }

        return new ByteArrayInputStream(out.toByteArray());
    }
    private void generatePassedFailedReport(PdfPCell cell,PdfPTable table,List<PricingTestCaseResponse> testCaseList,Font valueFont) {
        
        for (PricingTestCaseResponse testCases : testCaseList) {
        	cell = new PdfPCell(new Phrase(String.valueOf(testCases.getTestTransactionId()),valueFont));
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);

            cell = new PdfPCell(new Phrase(String.valueOf(testCases.getApplicationIdentity()),valueFont));
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);

            cell = new PdfPCell(new Phrase(String.valueOf(testCases.getBankDivision()),valueFont));
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);
            
            cell = new PdfPCell(new Phrase(String.valueOf(testCases.getProductFamily()),valueFont));
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);

            cell = new PdfPCell(new Phrase(String.valueOf(testCases.getProductName()),valueFont));
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);

            cell = new PdfPCell(new Phrase(String.valueOf(testCases.getBorrowingAmount()),valueFont));
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);
            
            cell = new PdfPCell(new Phrase(String.valueOf(testCases.getTermFactor()),valueFont));
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);

            cell = new PdfPCell(new Phrase(String.valueOf(testCases.getRiskBand()),valueFont));
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);

            cell = new PdfPCell(new Phrase(String.valueOf(testCases.getExpectetAir()),valueFont));
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);
            
            cell = new PdfPCell(new Phrase(String.valueOf(testCases.getExpectetApr()),valueFont));
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);

            cell = new PdfPCell(new Phrase(String.valueOf(testCases.getActualAir()),valueFont));
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);

            cell = new PdfPCell(new Phrase(String.valueOf(testCases.getActualApr()),valueFont));
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);
            
            if(null!=testCases.getTestTransactionFlag())
            if("Y".equalsIgnoreCase(testCases.getTestTransactionFlag().toString())) {
                cell = new PdfPCell(new Phrase(String.valueOf("Pass"),valueFont));
            }else {
                cell = new PdfPCell(new Phrase(String.valueOf("Fail"),valueFont));
            }
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);
        }
    }
}